Feature/create entities
betterhealth490/betterhealth pull request #12
Opened 2024-11-09 01:04 UTC by aloomdar

2024-11-09 01:05 UTC, tanvirlongia submitted a review, later dismissed

2024-11-12 00:41 UTC, jesuskcapellan requested changes
We should have two interfaces for each function, an input and result. There are four functions: Get (single instance), List (multiple instances), Update, and Create. 

Revise this commit to have an input interface and a result interface for the four functions, totaling 8 interfaces per file.

2024-11-13 01:39 UTC, jesuskcapellan approved these changes

2024-11-13 04:15 UTC, tanvirlongia approved these changes

2024-11-13 14:49 UTC, merged