Add journal use case
betterhealth490/betterhealth pull request #28
Opened 2024-11-16 07:53 UTC by tanvirlongia

2024-11-16 18:03 UTC, aloomdar reviewed
did you do unit testing?

2024-11-18 20:47 UTC, jesuskcapellan requested changes

2024-11-18 20:47 UTC, jesuskcapellan commented on src/use-cases/journal.ts
> +}
Do we need a delete function? The only reason I see for it would be when we delete a user but that shouldn't really necessitate a function.

2024-11-18 20:47 UTC, jesuskcapellan commented on src/use-cases/journal.ts
> +
Where is the createJournal function?

2024-11-18 20:49 UTC, jesuskcapellan commented
Also why is your PR 4 commits, most of which seem unrelated? You should be creating feature branches from the latest main branch, so as to only have relevant commits shown.

2024-11-19 19:34 UTC, jesuskcapellan approved these changes

2024-11-19 19:42 UTC, aloomdar approved these changes

2024-11-19 19:43 UTC, merged