Feature/inbox page
betterhealth490/betterhealth pull request #36
Opened 2024-11-26 06:45 UTC by DavidZamora35

Finished UI for patient inbox page. Still requires some use cases for receiving the user's list of therapists and their chat logs.

2024-11-26 16:53 UTC, jesuskcapellan commented
10 commits, nice

2024-11-27 01:13 UTC, oa279 approved these changes, later dismissed

2024-11-27 21:47 UTC, jesuskcapellan requested changes

2024-11-27 21:47 UTC, jesuskcapellan commented on src/app/(user)/inbox/page.tsx
I think to solve the height issue, you can try editing the `layout.tsx` file for `app/(user)/`. There should be a div that contains the Breadcrumbs component and the SidebarInset component. Just add `flex flex-col` to that div and then `flex-1` to the SidebarInset. Reach out for more.

2024-11-27 21:47 UTC, jesuskcapellan commented on src/app/(user)/inbox/mock-data.ts
Can we change the message up just so it's clearer that it's changing?

2024-11-27 21:47 UTC, jesuskcapellan commented on src/app/(user)/inbox/chat-box.tsx
> +                <div className="flex p-6 border-b-2 gap-4">
can we make the border 1 px to keep consistent?

2024-11-27 21:47 UTC, jesuskcapellan commented on public/demo.png
mogged.

2024-11-27 21:47 UTC, jesuskcapellan commented on src/app/(user)/inbox/chat-box.tsx
> +                            <Input
see if you can use the textarea component from shadcn, not sure how it works but could be fruitful???

2024-12-02 01:33 UTC, closed without merging