Add patient/therapist table and create new survey tables
betterhealth490/betterhealth pull request #48
Opened 2024-12-09 04:54 UTC by aloomdar

2024-12-10 19:59 UTC, jesuskcapellan requested changes

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +]);
we dont need this anymore. the questionaire is just for signups

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +]);
These are just mental health disorders, we need specialties like addiction, family, health, etc. (find more dont just use these)

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +export const sleepTimeEnum = pgEnum("sleep_time", ["Before 8 PM", "8 PM - 10 PM", "10 PM - Midnight", "After Midnight"]);
this should just be a number

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +export const selfImageEnum = pgEnum("self_image", ["Negative", "Neutral", "Positive"]);
theses should just be integers from 1-5. the front end will handle the naming

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +    .references(() => users.email),
we dont need these in this table

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +    .references(() => users.email),
same here

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
>    habitId: serial("habit_id").primaryKey(),
surveyid

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +);
dont know why this was added? we just need a single questionaire table

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
>      .notNull(),
also not needed

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +// });
delete dont comment out

2024-12-10 19:59 UTC, jesuskcapellan commented on src/db/schema.ts
> +  "Cancelled",
again why are we capitalizing it?

2024-12-10 20:41 UTC, jesuskcapellan requested changes
Remember to do `npm run build && npm run start` to simulate the prod environment. You also need to do `npm run db:push` to push your changes to our remote database. I'm pretty sure this commit might break our db.

2024-12-10 20:41 UTC, jesuskcapellan commented on src/entities/surveys.ts
you need to update this with the new values

2024-12-10 20:41 UTC, jesuskcapellan commented on src/data-access/surveys.ts
update these as well

2024-12-10 22:19 UTC, jesuskcapellan approved these changes

2024-12-11 03:08 UTC, tanvirlongia approved these changes

2024-12-11 03:09 UTC, merged